import {useEffect,useState} from 'react';
import {api} from '../lib/api';
import {Card,fmtBytes} from './AdminCorePanels';

function Input({l,k,f,s,type='text',placeholder=''}){return <label>{l}<input type={type} placeholder={placeholder} value={f[k]??''} onChange={e=>s({...f,[k]:e.target.value})}/></label>}
function TextCard({t,v}){return <div className="stat-card"><small>{t}</small><strong>{v??'—'}</strong></div>}
function DownloadCell({url}){
  if(!url)return <span>—</span>;
  return <div style={{maxWidth:360,wordBreak:'break-all'}}><a href={url} target="_blank" rel="noreferrer">打开下载地址</a><br/><small>{url}</small></div>
}

export default function AdminOpenListPanel(){
  const[info,setInfo]=useState(null),[f,setF]=useState({url:'https://yun.zonoeios.xyz',token:'',publicPathPrefix:'/d/a/app/',apiBasePath:'/',enabled:true}),[schedule,setSchedule]=useState({enabled:false,intervalMinutes:15,parseLimit:1}),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[results,setResults]=useState(null),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[missing,setMissing]=useState(null);
  const load=async(silent=false)=>{try{const r=await api.admin('/openlist');setInfo(r.data);const c=r.data?.config||{};setF(x=>({...x,url:c.url||x.url,publicPathPrefix:c.publicPathPrefix||'/d/a/app/',apiBasePath:c.apiBasePath||'/',enabled:c.enabled!==false,token:''}));setSchedule(r.data?.scheduler?{enabled:!!r.data.scheduler.enabled,intervalMinutes:Number(r.data.scheduler.intervalMinutes||15),parseLimit:Number(r.data.scheduler.parseLimit||1)}:{enabled:false,intervalMinutes:15,parseLimit:1})}catch(e){if(!silent)setNote(e.message)}};
  const loadResults=async(page=1,nextQ=q,nextStatus=status)=>{try{const r=await api.admin(`/openlist/results-rich?page=${page}&pageSize=50&status=${encodeURIComponent(nextStatus)}&q=${encodeURIComponent(nextQ||'')}`);setResults({items:r.data||[],meta:r.meta||{}})}catch(e){setNote(e.message)}};
  useEffect(()=>{load();loadResults(1,'','all')},[]);
  const taskState=info?.task?.state||'idle',running=['queued','running'].includes(taskState);
  useEffect(()=>{if(!running)return;const id=setInterval(()=>load(true),2000);return()=>clearInterval(id)},[running]);
  useEffect(()=>{if(['success','failed'].includes(taskState))loadResults(1,q,status)},[taskState]);
  const save=async()=>{setBusy(true);setNote('');try{const body={url:f.url,publicPathPrefix:f.publicPathPrefix,apiBasePath:f.apiBasePath,enabled:!!f.enabled};if(f.token.trim())body.token=f.token.trim();await api.admin('/openlist',{method:'PUT',body:JSON.stringify(body)});setNote('OpenList 配置已保存');await load()}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const saveSchedule=async()=>{setBusy(true);setNote('');try{await api.admin('/openlist/schedule',{method:'PUT',body:JSON.stringify({enabled:!!schedule.enabled,intervalMinutes:Number(schedule.intervalMinutes),parseLimit:Number(schedule.parseLimit)})});setNote('定时解析设置已保存；间隔和每轮数量按你的设置执行。');await load()}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const test=async()=>{setBusy(true);setNote('正在测试 OpenList…');try{const r=await api.admin('/openlist/test',{method:'POST',body:'{}'});setNote(`连接正常 · 目录条目 ${Number(r.data.total||0).toLocaleString()} · ${r.data.provider||'unknown'}`)}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const sync=async(parseLimit,forceListRefresh=false)=>{if(forceListRefresh&&!confirm('强制刷新会绕过 ZONOE 目录缓存，但 OpenList 请求仍使用 refresh=false。确定继续？'))return;if(parseLimit>0&&!confirm(`后台最多解析 ${parseLimit} 个新增/变化 IPA，继续？`))return;try{await api.admin('/openlist/sync',{method:'POST',body:JSON.stringify({parseLimit,forceListRefresh})});setNote(parseLimit?'解析任务已启动':'MD5 扫描任务已启动');await load(true)}catch(e){setNote(e.message)}};
  const loadMissing=async()=>{try{const r=await api.admin('/openlist/missing?page=1&pageSize=100');setMissing(r)}catch(e){setNote(e.message)}};
  const c=info?.cache||{},task=info?.task||{},p=task.progress||{},rm=results?.meta||{},counts=rm.counts||{},ru=info?.rangeUsage||{},hour=ru.hour||{},day=ru.day||{};
  return <div className="admin-panel"><h2>OpenList IPA 元数据</h2><p>负责发现 IPA、MD5 对比和 Range 解析。目录列表优先使用 30 分钟 ZONOE 缓存；OpenList 列目录使用单次 <code>per_page=0</code> 且 <code>refresh=false</code>。真正访问网盘直链的 Range Parser 单并发执行，并持续记录请求次数与实际读取流量。</p>{note&&<div className="toast">{note}</div>}<div className="form-grid"><Input l="OpenList URL" k="url" f={f} s={setF}/><Input l={info?.config?.tokenConfigured?'OpenList 令牌（留空不修改）':'OpenList 令牌'} k="token" f={f} s={setF} type="password" placeholder="填写 OpenList 设置 → 其他 → 令牌"/><Input l="公开下载路径前缀" k="publicPathPrefix" f={f} s={setF}/><Input l="API Base Path" k="apiBasePath" f={f} s={setF}/><label>启用<input type="checkbox" checked={!!f.enabled} onChange={e=>setF({...f,enabled:e.target.checked})}/></label></div><div className="actions"><button className="primary" disabled={busy} onClick={save}>保存配置</button><button disabled={busy||!info?.config?.tokenConfigured} onClick={test}>测试连接</button><button disabled={running||!info?.config?.tokenConfigured} onClick={()=>sync(0,false)}>后台扫描 MD5（使用缓存）</button><button disabled={running||!info?.config?.tokenConfigured} onClick={()=>sync(0,true)}>强制刷新目录</button><button disabled={running||!info?.config?.tokenConfigured} onClick={()=>sync(1,false)}>后台解析 1 个</button></div>
  <div className="admin-panel"><h3>定时解析</h3><p>建议默认每 15 分钟解析 1 个，但不固定。你可以设置 5–1440 分钟、每轮 1–20 个；后台仍保持单并发串行解析。</p><div className="form-grid"><label>启用定时<input type="checkbox" checked={!!schedule.enabled} onChange={e=>setSchedule({...schedule,enabled:e.target.checked})}/></label><label>每 X 分钟<input type="number" min="5" max="1440" value={schedule.intervalMinutes} onChange={e=>setSchedule({...schedule,intervalMinutes:e.target.value})}/></label><label>每次解析 X 个<input type="number" min="1" max="20" value={schedule.parseLimit} onChange={e=>setSchedule({...schedule,parseLimit:e.target.value})}/></label></div><div className="actions"><button className="primary" disabled={busy} onClick={saveSchedule}>保存定时设置</button></div></div>
  <div className="stat-grid"><Card t="缓存文件" v={c.files}/><Card t="已解析" v={c.parsed}/><Card t="待解析" v={c.pending}/><Card t="解析失败" v={c.failed}/></div>
  <div className="admin-panel"><h3>Range Parser 用量</h3><div className="stat-grid"><TextCard t="本小时" v={Number(hour.attempts||0).toLocaleString()}/><TextCard t="今日" v={Number(day.attempts||0).toLocaleString()}/><TextCard t="今日 Range 请求" v={Number(day.rangeRequests||0).toLocaleString()}/><TextCard t="今日真实读取" v={fmtBytes(day.rangeBytes||0)}/></div></div>
  {taskState!=='idle'&&<div className="admin-panel"><h3>后台任务实时进度</h3><div className="row"><b>{taskState} · {task.stage||'—'}</b><span>{task.message||'—'}</span></div><div className="row"><b>数据库匹配</b><span>引用 {p.databaseRefs||0} · 唯一 IPA {p.uniqueFiles||0} · 缺失 {p.missingFiles||0} · MD5复用 {p.metadataReusedByMd5||0}</span></div><div className="row"><b>IPA 解析</b><span>{p.parseDone||0}/{p.parseTarget||0} · 成功 {p.parsedSuccess||0} · 失败 {p.parsedFailed||0}</span></div><div className="row"><b>Range 流量</b><span>{p.rangeRequestsNow||0} 次 · {fmtBytes(p.rangeBytesNow||0)}</span></div></div>}
  <div className="admin-panel"><h3>解析结果库</h3><div className="inline-form"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索 App / Bundle ID / 版本 / IPA"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部</option><option value="parsed">已解析</option><option value="pending">待解析</option><option value="failed">解析失败</option><option value="mismatch">版本/大小异常</option></select><button onClick={()=>loadResults(1,q,status)}>搜索</button><button onClick={loadMissing}>缺失条目</button></div><div className="row"><b>结果统计</b><span>全部 {counts.all||0} · 已解析 {counts.parsed||0} · 待解析 {counts.pending||0} · 失败 {counts.failed||0} · 异常 {counts.mismatch||0}</span></div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">App</th><th align="left">版本信息</th><th align="left">IPA 信息</th><th align="left">下载地址</th><th align="left">状态</th></tr></thead><tbody>{results?.items?.map(x=><tr key={x.appKey} style={{borderTop:'1px solid #e5e7eb',verticalAlign:'top'}}><td style={{padding:8}}><b>{x.appName||x.packageName||x.fileName}</b><br/><small>{x.sourceName} · ID {x.legacyId}</small></td><td style={{padding:8}}><div>源版本：{x.sourceVersion||'—'}</div><div>IPA 版本：{x.packageVersion||'—'}</div><div>Build：{x.packageBuild||'—'}</div></td><td style={{padding:8,wordBreak:'break-all'}}>{x.bundleId||'—'}<br/>最低 iOS {x.minimumIos||'—'} · {fmtBytes(x.size)}<br/><small>Range {x.rangeRequests||0} 次 · {fmtBytes(x.rangeBytes||0)}</small></td><td style={{padding:8}}><DownloadCell url={x.downloadUrl}/></td><td style={{padding:8}}>{x.parseStatus==='parsed'?'已解析':x.parseStatus==='failed'?'失败':'待解析'}{x.mismatch?' · 需核对':''}</td></tr>)}</tbody></table></div>{results?.meta&&<div className="actions"><button disabled={Number(rm.page||1)<=1} onClick={()=>loadResults(Number(rm.page||1)-1,q,status)}>上一页</button><span>第 {rm.page||1} 页 · {rm.total||0} 条</span><button disabled={Number(rm.page||1)*Number(rm.pageSize||50)>=Number(rm.total||0)} onClick={()=>loadResults(Number(rm.page||1)+1,q,status)}>下一页</button></div>}</div>
  {missing&&<div className="admin-panel"><h3>缺失 IPA 对应数据库条目</h3><p>这里的下载地址来自软件源数据库。即使 OpenList 清单里没有找到文件，也保留原数据库地址，方便直接排查。</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">App</th><th align="left">源版本</th><th align="left">下载地址</th><th align="left">预期 OpenList 路径</th></tr></thead><tbody>{missing.data?.map(x=><tr key={x.appKey} style={{borderTop:'1px solid #e5e7eb',verticalAlign:'top'}}><td style={{padding:8}}><b>{x.name||'—'}</b><br/><small>{x.sourceName} · ID {x.legacyId}</small></td><td style={{padding:8}}>{x.version||'—'}</td><td style={{padding:8}}><DownloadCell url={x.downloadUrl}/></td><td style={{padding:8,wordBreak:'break-all'}}><small>{x.apiPath||'—'}</small></td></tr>)}</tbody></table></div></div>}
  </div>
}
