import {useEffect,useState} from 'react';
import {api} from '../lib/api';

const fmt=n=>{n=Number(n||0);if(n<1024)return `${n} B`;if(n<1024**2)return `${(n/1024).toFixed(1)} KB`;return `${(n/1024**2).toFixed(2)} MB`};
export default function AdminCachePanel(){
  const[info,setInfo]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
  const load=()=>api.admin('/cache').then(r=>setInfo(r.data)).catch(e=>setMsg(e.message));
  useEffect(()=>{load()},[]);
  const clear=async(target,label)=>{if(!confirm(`确定${label}？不会删除 OpenList 上的 IPA，也不会删除 MySQL 软件源数据。`))return;setBusy(true);setMsg('');try{const r=await api.admin('/cache/clear',{method:'POST',body:JSON.stringify({target})});setInfo(r.data);setMsg(target==='failed'?`已重置 ${Number(r.data.resetFailed||0)} 条失败记录`:`${label}完成`)}catch(e){setMsg(e.message)}finally{setBusy(false)}};
  const i=info?.ipa||{},d=info?.directory||{},t=info?.task||{};
  return <div className="admin-panel"><h2>本地缓存管理</h2><p>只管理 ZONOE 本机的解析/目录缓存。解析结果同时进入按 IPA MD5 保存的持久元数据库，因此更换云盘账号、挂载路径或下载地址后，只要 IPA 内容和大小一致就能重新关联。任何清理操作都不会删除 OpenList IPA，也不会修改 MySQL 业务数据。</p>{msg&&<div className="toast">{msg}</div>}<div className="stat-grid"><div className="stat-card"><small>总缓存占用</small><strong>{fmt(info?.totalBytes)}</strong></div><div className="stat-card"><small>IPA 缓存文件</small><strong>{Number(i.files||0).toLocaleString()}</strong></div><div className="stat-card"><small>MD5 解析库</small><strong>{Number(i.metadataLibraryEntries||0).toLocaleString()}</strong></div><div className="stat-card"><small>失败记录</small><strong>{Number(i.failed||0).toLocaleString()}</strong></div></div><div className="row"><b>当前 IPA 元数据缓存</b><span>{fmt(i.bytes)} · 已解析 {i.parsed||0} · 待解析 {i.pending||0} · 最后文件更新 {i.updatedAt?new Date(i.updatedAt).toLocaleString():'—'}</span></div><div className="row"><b>MD5 持久解析库</b><span>{fmt(i.metadataLibraryBytes)} · {Number(i.metadataLibraryEntries||0).toLocaleString()} 个内容指纹 · 不绑定 OpenList 账号/路径</span></div><div className="row"><b>OpenList 目录缓存</b><span>{fmt(d.bytes)} · {d.directories||0} 个目录 · {d.updatedAt?new Date(d.updatedAt).toLocaleString():'—'}</span></div><div className="row"><b>后台任务状态</b><span>{t.state||'idle'} · {t.stage||'idle'} · {t.updatedAt?new Date(t.updatedAt).toLocaleString():'—'}</span></div><div className="admin-panel"><h3>缓存操作</h3><p>“清理失败记录”会让失败 IPA 重新进入待解析队列；“清空 IPA 解析缓存”会同时清空当前路径缓存和 MD5 持久解析库，需要重新解析。不会删除云盘文件。</p><div className="actions"><button disabled={busy} onClick={()=>clear('directory','清空 OpenList 目录缓存')}>清空目录缓存</button><button disabled={busy||!i.failed} onClick={()=>clear('failed','重置解析失败记录')}>重置失败记录</button><button disabled={busy} onClick={()=>clear('ipa','清空 IPA 解析缓存')}>清空 IPA 解析缓存</button><button disabled={busy} onClick={()=>clear('all','清空全部本地缓存')}>清空全部缓存</button><button disabled={busy} onClick={load}>刷新状态</button></div></div></div>
}