import {useEffect,useState} from 'react';
import {Link} from 'react-router-dom';
import {api} from '../lib/api';

const emptyApp={name:'',slug:'',bundleId:'',iconUrl:'',shortDescription:'',description:'',developer:'',status:'draft',featured:false,hot:false,sortOrder:0};

export default function Admin(){
  const[tab,setTab]=useState('dashboard'),[stats,setStats]=useState(null),[apps,setApps]=useState([]),[categories,setCategories]=useState([]),[sources,setSources]=useState([]),[form,setForm]=useState(null),[msg,setMsg]=useState('');
  const guard=p=>p.catch(e=>{if(/登录/.test(e.message))window.location.assign('/login');else setMsg(e.message)});
  const refresh=()=>guard(Promise.all([api.admin('/statistics'),api.admin('/apps?pageSize=100'),api.admin('/categories'),api.admin('/sources')]).then(([s,a,c,d])=>{setStats(s.data);setApps(a.data);setCategories(c.data);setSources(d.data)}));
  useEffect(refresh,[]);
  const saveApp=async()=>{const body={...form,categoryId:form.categoryId?Number(form.categoryId):null};if(form.id)await api.admin(`/apps/${form.id}`,{method:'PUT',body:JSON.stringify(body)});else await api.admin('/apps',{method:'POST',body:JSON.stringify(body)});setForm(null);refresh()};
  const title=tab==='dashboard'?'工作台':tab==='apps'?'应用管理':tab==='categories'?'分类管理':tab==='sources'?'下载源管理':tab==='update'?'系统更新':'设置';
  return <div className="admin-shell"><aside><div className="admin-brand">ZONOE<br/><small>后台管理</small></div>{[['dashboard','工作台'],['apps','应用管理'],['categories','分类管理'],['sources','下载源'],['settings','设置'],['update','在线更新']].map(([k,n])=><button className={tab===k?'active':''} key={k} onClick={()=>setTab(k)}>{n}</button>)}<Link to="/">返回前台</Link></aside><section className="admin-main"><header><h1>{title}</h1><span>手机和桌面均可完整操作</span></header>{msg&&<div className="toast">{msg}<button onClick={()=>setMsg('')}>×</button></div>}
  {tab==='dashboard'&&stats&&<><div className="stat-grid"><Card t="App 总数" v={stats.totalApps}/><Card t="IPA 版本" v={stats.totalVersions}/><Card t="今日下载" v={stats.todayDownloads}/><Card t="总下载量" v={stats.totalDownloads}/></div><div className="admin-panel"><h2>热门 App</h2>{stats.hotApps.map((x,i)=><div className="row" key={x.id}><b>{i+1}. {x.name}</b><span>{x.download_count} 次</span></div>)}</div></>}
  {tab==='apps'&&<div className="admin-panel"><div className="panel-head"><button className="primary" onClick={()=>setForm({...emptyApp})}>+ 新增 App</button></div><div className="admin-list">{apps.map(a=><div className="admin-app" key={a.id}><img src={a.icon_url||'/placeholder.svg'}/><div><b>{a.name}</b><small>{a.bundle_id}</small><small>{a.version||'无版本'} · {a.status}</small></div><button onClick={()=>setForm({id:a.id,name:a.name,slug:a.slug,bundleId:a.bundle_id,iconUrl:a.icon_url||'',shortDescription:a.short_description||'',description:a.description||'',developer:a.developer||'',categoryId:a.category_id||'',status:a.status,featured:a.featured,hot:a.hot,sortOrder:a.sort_order})}>编辑</button><button onClick={async()=>{if(confirm('确定删除？')){await api.admin(`/apps/${a.id}`,{method:'DELETE'});refresh()}}}>删除</button></div>)}</div></div>}
  {tab==='categories'&&<CategoryManager items={categories} refresh={refresh}/>} 
  {tab==='sources'&&<SourceManager items={sources} refresh={refresh}/>} 
  {tab==='settings'&&<Settings/>}
  {tab==='update'&&<SystemUpdate/>}
  {form&&<div className="modal"><div className="modal-card"><h2>{form.id?'编辑 App':'新增 App'}</h2><div className="form-grid"><Input l="名称" k="name" f={form} s={setForm}/><Input l="Slug" k="slug" f={form} s={setForm}/><Input l="Bundle ID" k="bundleId" f={form} s={setForm}/><Input l="图标 URL" k="iconUrl" f={form} s={setForm}/><Input l="开发者" k="developer" f={form} s={setForm}/><label>分类<select value={form.categoryId||''} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">未分类</option>{categories.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></label><label>状态<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="draft">草稿</option><option value="published">上架</option><option value="unlisted">下架</option></select></label><label>推荐<input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/></label><label>热门<input type="checkbox" checked={form.hot} onChange={e=>setForm({...form,hot:e.target.checked})}/></label><label className="full">简短介绍<textarea value={form.shortDescription} onChange={e=>setForm({...form,shortDescription:e.target.value})}/></label><label className="full">详细介绍<textarea rows="6" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label></div><div className="actions"><button onClick={()=>setForm(null)}>取消</button><button className="primary" onClick={saveApp}>保存</button></div>{form.id&&<VersionManager appId={form.id} sources={sources}/>}</div></div>}
  </section></div>
}

function Card({t,v}){return <div className="stat-card"><small>{t}</small><strong>{Number(v||0).toLocaleString()}</strong></div>}
function Input({l,k,f,s}){return <label>{l}<input value={f[k]||''} onChange={e=>s({...f,[k]:e.target.value})}/></label>}
function CategoryManager({items,refresh}){const[n,setN]=useState(''),[slug,setSlug]=useState('');return <div className="admin-panel"><div className="inline-form"><input placeholder="分类名" value={n} onChange={e=>setN(e.target.value)}/><input placeholder="slug" value={slug} onChange={e=>setSlug(e.target.value)}/><button className="primary" onClick={async()=>{await api.admin('/categories',{method:'POST',body:JSON.stringify({name:n,slug})});setN('');setSlug('');refresh()}}>新增</button></div>{items.map(x=><div className="row" key={x.id}><b>{x.name}</b><span>{x.slug}</span><button onClick={async()=>{await api.admin(`/categories/${x.id}`,{method:'DELETE'});refresh()}}>删除</button></div>)}</div>}
function SourceManager({items,refresh}){const[f,setF]=useState({name:'',type:'openlist',baseUrl:'',priority:100});return <div className="admin-panel"><div className="form-grid"><Input l="名称" k="name" f={f} s={setF}/><label>类型<select value={f.type} onChange={e=>setF({...f,type:e.target.value})}>{['local','http','openlist','cloud','cdn','s3','oss','r2','other'].map(x=><option key={x}>{x}</option>)}</select></label><Input l="Base URL" k="baseUrl" f={f} s={setF}/><Input l="优先级" k="priority" f={f} s={setF}/></div><button className="primary" onClick={async()=>{await api.admin('/sources',{method:'POST',body:JSON.stringify({...f,priority:Number(f.priority)})});setF({name:'',type:'openlist',baseUrl:'',priority:100});refresh()}}>新增下载源</button>{items.map(x=><div className="row" key={x.id}><b>{x.name}</b><span>{x.type} · P{x.priority}</span><span>{x.base_url}</span><button onClick={async()=>{await api.admin(`/sources/${x.id}`,{method:'DELETE'});refresh()}}>删除</button></div>)}</div>}
function Settings(){const[k,setK]=useState('site_notice'),[v,setV]=useState('');return <div className="admin-panel"><p>修改公开站点设置。常用 key：site_name、site_notice、hero_title</p><div className="inline-form"><input value={k} onChange={e=>setK(e.target.value)}/><input value={v} onChange={e=>setV(e.target.value)} placeholder="值"/><button className="primary" onClick={()=>api.admin(`/settings/${k}`,{method:'PUT',body:JSON.stringify({value:v,isPublic:true})})}>保存</button></div></div>}

function SystemUpdate(){
  const[info,setInfo]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=async(silent=false)=>{if(!silent)setLoading(true);try{const r=await api.admin('/system/update');setInfo(r.data);setError('')}catch(e){if(!silent)setError(e.message)}finally{if(!silent)setLoading(false)}};
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(!['queued','running'].includes(info?.status?.state))return;const id=setInterval(()=>load(true),2500);return()=>clearInterval(id)},[info?.status?.state]);
  const start=async(force=false)=>{const text=force?'确定从 GitHub 重新安装当前 Stable 版本？更新前会自动备份。':'确定立即从 GitHub 在线更新？更新前会自动备份，更新过程中后台会短暂断开。';if(!window.confirm(text))return;setError('');try{const r=await api.admin('/system/update',{method:'POST',body:JSON.stringify({force})});setInfo(x=>({...x,status:r.data}));setTimeout(()=>load(true),1000)}catch(e){setError(e.message)}};
  const state=info?.status?.state||'idle';const running=['queued','running'].includes(state);
  return <div className="admin-panel"><h2>GitHub 在线更新</h2><p>在这里检查版本并直接更新。更新任务由独立的 root systemd updater 执行，后台 API 本身不拥有 root 权限。</p>{loading&&<p>正在检查 GitHub...</p>}{error&&<div className="toast">{error}</div>}{info&&<><div className="row"><b>当前版本</b><span>{info.currentVersion}</span></div><div className="row"><b>最新版本</b><span>{info.latestVersion||'暂未获取'}</span></div><div className="row"><b>更新通道</b><span>{info.channel} · {info.repository}</span></div><div className="row"><b>任务状态</b><span>{state} · {info.status?.message||'—'}</span></div>{info.remoteError&&<p className="error">GitHub 检查失败：{info.remoteError}</p>}{info.release?.notes&&<div style={{margin:'16px 0',whiteSpace:'pre-wrap',maxHeight:240,overflow:'auto'}}><b>更新说明</b><p>{info.release.notes}</p></div>}<div className="actions"><button onClick={()=>load()} disabled={running}>检查更新</button><button className="primary" onClick={()=>start(false)} disabled={running||!info.hasUpdate}>{running?'正在更新…':info.hasUpdate?`更新到 ${info.latestVersion}`:'已是最新版本'}</button>{!running&&!info.hasUpdate&&info.latestVersion&&<button onClick={()=>start(true)}>重新安装当前版本</button>}</div>{state==='success'&&<p>更新完成：{info.status?.fromVersion||'—'} → {info.status?.toVersion||info.currentVersion}。建议刷新后台页面。</p>}{state==='failed'&&<p className="error">{info.status?.message||'更新失败'}。服务器日志：data/update-runtime/admin-update.log</p>}</>}</div>
}

function VersionManager({appId,sources}){const[versions,setV]=useState([]),[f,setF]=useState({version:'',build:'',target:'',sourceId:sources[0]?.id||'',fileSize:''});const load=()=>api.admin(`/apps/${appId}`).then(x=>setV(x.data.versions||[]));useEffect(load,[appId]);return <div className="versions-admin"><h3>版本管理</h3><div className="form-grid"><Input l="Version" k="version" f={f} s={setF}/><Input l="Build" k="build" f={f} s={setF}/><Input l="File Size(bytes)" k="fileSize" f={f} s={setF}/><label>下载源<select value={f.sourceId} onChange={e=>setF({...f,sourceId:e.target.value})}>{sources.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select></label><Input l="Target / URL / 路径" k="target" f={f} s={setF}/></div><button className="primary" onClick={async()=>{await api.admin(`/apps/${appId}/versions`,{method:'POST',body:JSON.stringify({version:f.version,build:f.build,fileSize:f.fileSize?Number(f.fileSize):null,sources:f.sourceId&&f.target?[{sourceId:Number(f.sourceId),target:f.target,priority:10}]:[]})});setF({...f,version:'',build:'',target:'',fileSize:''});load()}}>新增版本</button>{versions.map(v=><div className="row" key={v.id}><b>{v.version} ({v.build||'—'})</b><span>{v.status}</span><button onClick={async()=>{await api.admin(`/versions/${v.id}`,{method:'DELETE'});load()}}>删除</button></div>)}</div>}
