import {useEffect,useState} from 'react';
import {api} from '../lib/api';

const strategyLabels={preview:'只预览，不写入',changed:'值变化时更新',empty:'仅数据库为空时填充',always:'始终以 IPA 为准'};
export default function AdminWriteBackPanel({sources=[]}){
  const[sourceId,setSourceId]=useState(''),[info,setInfo]=useState(null),[preview,setPreview]=useState(null),[history,setHistory]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[previewFilter,setPreviewFilter]=useState('all');
  useEffect(()=>{if(!sourceId&&sources.length)setSourceId(String(sources[0].id))},[sources,sourceId]);
  const load=async id=>{if(!id)return;setMsg('');try{const[r,h]=await Promise.all([api.admin(`/sources/${id}/writeback`),api.admin(`/sources/${id}/writeback/history?limit=30`)]);setInfo(r.data);setHistory(h.data?.items||[]);setPreview(null);setPreviewFilter('all')}catch(e){setMsg(e.message)}};
  useEffect(()=>{if(sourceId)load(sourceId)},[sourceId]);
  const setTop=(key,value)=>setInfo(x=>({...x,config:{...x.config,[key]:value}}));
  const setMapping=(key,patch)=>setInfo(x=>({...x,config:{...x.config,mappings:{...x.config.mappings,[key]:{...x.config.mappings[key],...patch}}}}));
  const save=async()=>{if(!sourceId||!info)return;setBusy(true);setMsg('');try{const r=await api.admin(`/sources/${sourceId}/writeback`,{method:'PUT',body:JSON.stringify(info.config)});setInfo(r.data);setMsg('字段映射和写回策略已保存')}catch(e){setMsg(e.message)}finally{setBusy(false)}};
  const runPreview=async()=>{if(!sourceId)return;setBusy(true);setMsg('');try{const r=await api.admin(`/sources/${sourceId}/writeback/preview?limit=50`);setPreview(r.data);setPreviewFilter('all');setMsg(`预览完成：扫描 ${r.data.scanned||0} 个已解析 App，${r.data.changeApps||0} 个存在可写变化`)}catch(e){setMsg(e.message)}finally{setBusy(false)}};
  const applyPreview=async()=>{const keys=(preview?.items||[]).filter(x=>x.writeCount>0).map(x=>x.appKey);if(!keys.length)return setMsg('当前预览没有需要写入的变化');if(!confirm(`确定把预览中的 ${keys.length} 个已有 App 按当前规则写回数据库？不会新增 App。`))return;setBusy(true);setMsg('');try{const r=await api.admin(`/sources/${sourceId}/writeback/apply`,{method:'POST',body:JSON.stringify({limit:200,appKeys:keys})});setMsg(`同步完成：更新 ${r.data.apps||0} 个 App / ${r.data.applied||0} 个字段，失败 ${r.data.failed||0}`);await load(sourceId);await runPreview()}catch(e){setMsg(e.message)}finally{setBusy(false)}};
  if(!sources.length)return <div className="admin-panel"><h2>数据同步</h2><p>请先添加 MySQL 软件源。</p></div>;
  const cfg=info?.config||{},columns=info?.columns||[],fields=info?.fields||[],previewItems=(preview?.items||[]).filter(item=>previewFilter==='all'||(previewFilter==='diff'&&Number(item.previewCount||0)>0)||(previewFilter==='write'&&Number(item.writeCount||0)>0));
  return <div className="admin-panel"><h2>IPA 解析结果 → MySQL 字段同步</h2><p>默认关闭。只更新已经存在的 App，不自动 INSERT 新记录。你可以逐字段选择是否参与写回、目标数据库列和写回策略；未勾选的字段永远不会被修改。</p>{msg&&<div className="toast">{msg}</div>}<div className="row"><b>选择软件源</b><select value={sourceId} onChange={e=>setSourceId(e.target.value)}>{sources.map(s=><option key={s.id} value={s.id}>{s.name} · {s.database}/{s.table}</option>)}</select></div>{info&&<><div className="admin-panel"><h3>软件源级保护</h3><div className="form-grid"><label>允许 ZONOE 写回已有 App<input type="checkbox" checked={!!cfg.enabled} onChange={e=>setTop('enabled',e.target.checked)}/></label><label>解析后自动写回<input type="checkbox" disabled={!cfg.enabled} checked={!!cfg.autoApply} onChange={e=>setTop('autoApply',e.target.checked)}/></label></div><p>“自动写回”由后台安全调度器执行，只处理当前 MD5 已验证的解析结果，并且仍受下面每个字段的映射/策略限制。</p></div>
  <div className="admin-panel"><h3>字段映射</h3><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">IPA 解析字段</th><th align="left">参与同步</th><th align="left">数据库字段</th><th align="left">写回策略</th></tr></thead><tbody>{fields.map(field=>{const m=cfg.mappings?.[field.key]||{};return <tr key={field.key} style={{borderTop:'1px solid #e5e7eb'}}><td style={{padding:'10px 6px'}}><b>{field.label}</b><br/><small>{field.key}</small></td><td style={{padding:'10px 6px'}}><input type="checkbox" checked={!!m.enabled} onChange={e=>setMapping(field.key,{enabled:e.target.checked})}/></td><td style={{padding:'10px 6px'}}><select value={m.column||''} onChange={e=>setMapping(field.key,{column:e.target.value})}><option value="">不映射</option>{columns.map(c=><option key={c.name} value={c.name}>{c.name} · {c.type}</option>)}</select></td><td style={{padding:'10px 6px'}}><select value={m.strategy||'preview'} onChange={e=>setMapping(field.key,{strategy:e.target.value})}>{Object.entries(strategyLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></td></tr>})}</tbody></table></div><div className="actions"><button className="primary" disabled={busy} onClick={save}>保存字段映射</button><button disabled={busy} onClick={runPreview}>预览前 50 个已解析 App</button></div></div>
  {preview&&<div className="admin-panel"><h3>写回预览</h3><p>扫描 {preview.scanned||0} 个 · 有可写变化 {preview.changeApps||0} 个 · 可写字段 {preview.writeFields||0} 个。策略为“只预览”的字段会显示差异，但不会写入。</p><div className="inline-form"><select value={previewFilter} onChange={e=>setPreviewFilter(e.target.value)}><option value="all">全部已扫描 App</option><option value="diff">仅有字段差异</option><option value="write">仅可写变化</option></select><span>当前显示 {previewItems.length}/{preview.items?.length||0} 个 App</span></div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">App</th><th align="left">字段变化</th></tr></thead><tbody>{previewItems.map(item=><tr key={item.appKey} style={{borderTop:'1px solid #e5e7eb',verticalAlign:'top'}}><td style={{padding:'10px 6px',minWidth:180}}><b>{item.appName||item.appKey}</b><br/><small>ID {item.legacyId} · {item.appKey}</small></td><td style={{padding:'10px 6px'}}>{item.changes?.length?item.changes.map((c,i)=><div key={`${c.field}-${i}`}><b>{c.label}</b> → <code>{c.column}</code>：{c.before||'（空）'} → {c.next} · {strategyLabels[c.strategy]} {c.willWrite?<strong>【会写入】</strong>:<span>【不写入】</span>}</div>):<span>无差异：当前映射字段与 IPA 解析结果一致，无需写入。</span>}</td></tr>)}</tbody></table></div>{previewItems.length===0&&<p>当前筛选没有结果。</p>}<div className="actions"><button className="primary" disabled={busy||!cfg.enabled||!preview.writeFields} onClick={applyPreview}>确认同步预览中的变化</button></div></div>}
  <div className="admin-panel"><h3>最近写回历史</h3>{history.length===0?<p>暂无写回记录。</p>:history.map((x,i)=><div className="row" key={`${x.at}-${x.appKey}-${i}`}><b>{x.status==='success'?'成功':'失败'} · {x.appName||x.appKey}</b><span>{x.at?new Date(x.at).toLocaleString():'—'} · {x.mode==='auto'?'自动':'手动'} · {(x.changes||[]).map(c=>`${c.column}: ${c.before||'空'} → ${c.next}`).join('；')}{x.error?` · ${x.error}`:''}</span></div>)}</div></>}</div>
}
