import {useEffect,useState} from 'react';
import {api} from '../lib/api';

export function Card({t,v}){return <div className="stat-card"><small>{t}</small><strong>{Number(v||0).toLocaleString()}</strong></div>}
export function fmtBytes(n){n=Number(n||0);if(!n)return '—';return n>=1024**3?`${(n/1024**3).toFixed(2)} GB`:`${(n/1024**2).toFixed(1)} MB`}
function Input({l,k,f,s,type='text',placeholder=''}){return <label>{l}<input type={type} placeholder={placeholder} value={f[k]??''} onChange={e=>s({...f,[k]:e.target.value})}/></label>}

export function DashboardPanel({stats}){
  if(!stats)return <div className="admin-panel">加载中…</div>;
  return <><div className="stat-grid"><Card t="聚合 App" v={stats.totalApps}/><Card t="软件源" v={stats.totalSources}/><Card t="源内热度" v={stats.totalDownloads}/></div><div className="admin-panel"><h2>热门 App</h2>{stats.hotApps?.map((x,i)=><div className="row" key={x.id}><b>{i+1}. {x.name}</b><span>{x.source_name} · 热度 {Number(x.download_count||0).toLocaleString()}</span></div>)}</div></>
}

export function AppsPanel({items}){
  return <div className="admin-panel"><p>这里聚合多个 MySQL 软件源。默认只读；只有在“数据同步”里明确启用的软件源/字段才允许被 IPA 解析结果写回。</p><div className="admin-list">{items.map(a=><div className="admin-app" key={a.id}><img src={a.icon_url||'/placeholder.svg'}/><div><b>{a.name}</b><small>{a.source_name} · 原 ID {a.legacy_id}</small><small>v{a.version||'—'} · {fmtBytes(a.file_size)}{a.package_version?` · IPA ${a.package_version}`:''}</small></div><a href={`/app/${encodeURIComponent(a.id)}`} target="_blank" rel="noreferrer">查看</a></div>)}</div></div>
}

const blankSource={name:'',slug:'',host:'127.0.0.1',port:3306,database:'',username:'',password:'',table:'fa_category',priority:100,enabled:true};
export function SourceManager({items,refresh}){
  const[f,setF]=useState({...blankSource}),[editing,setEditing]=useState(null),[note,setNote]=useState('');
  const reset=()=>{setF({...blankSource});setEditing(null)};
  const edit=x=>{setEditing(x.id);setF({name:x.name,slug:x.slug,host:x.host,port:x.port,database:x.database,username:x.username,password:'',table:x.table||'fa_category',priority:x.priority,enabled:x.enabled})};
  const save=async()=>{setNote('');const body={...f,port:Number(f.port),priority:Number(f.priority),enabled:!!f.enabled};if(editing&&!body.password)delete body.password;try{if(editing)await api.admin(`/sources/${editing}`,{method:'PUT',body:JSON.stringify(body)});else await api.admin('/sources',{method:'POST',body:JSON.stringify(body)});reset();await refresh()}catch(e){setNote(e.message)}};
  const test=async id=>{setNote('正在测试连接…');try{await api.admin(`/sources/${id}/test`,{method:'POST',body:'{}'});setNote('MySQL 连接正常')}catch(e){setNote(e.message)}};
  return <div className="admin-panel"><h2>{editing?'编辑 MySQL 软件源':'新增 MySQL 软件源'}</h2><p>字段写回不在这里开启，请到“数据同步”逐个软件源配置。这样修改连接信息不会意外改变数据库写权限。</p>{note&&<div className="toast">{note}</div>}<div className="form-grid"><Input l="名称" k="name" f={f} s={setF}/><Input l="Slug" k="slug" f={f} s={setF} placeholder="例如 app2"/><Input l="MySQL Host" k="host" f={f} s={setF}/><Input l="Port" k="port" f={f} s={setF}/><Input l="Database" k="database" f={f} s={setF}/><Input l="Username" k="username" f={f} s={setF}/><Input l={editing?'Password（留空不修改）':'Password'} k="password" f={f} s={setF} type="password"/><Input l="应用表" k="table" f={f} s={setF}/><Input l="优先级" k="priority" f={f} s={setF}/><label>启用<input type="checkbox" checked={!!f.enabled} onChange={e=>setF({...f,enabled:e.target.checked})}/></label></div><div className="actions">{editing&&<button onClick={reset}>取消</button>}<button className="primary" onClick={save}>{editing?'保存修改':'新增软件源'}</button></div><h2>已配置软件源</h2>{items.map(x=><div className="row" key={x.id}><b>{x.name}</b><span>{x.enabled?'启用':'停用'} · {x.host}:{x.port}/{x.database} · {x.table}</span><button onClick={()=>test(x.id)}>测试</button><button onClick={()=>edit(x)}>编辑</button><button onClick={async()=>{if(confirm(`确定删除软件源 ${x.name}？不会删除原数据库数据。`)){await api.admin(`/sources/${x.id}`,{method:'DELETE'});refresh()}}}>删除</button></div>)}</div>
}

export function OpenListManager(){
  const[info,setInfo]=useState(null),[f,setF]=useState({url:'https://yun.zonoeios.xyz',token:'',publicPathPrefix:'/d/a/app/',apiBasePath:'/',enabled:true}),[schedule,setSchedule]=useState({enabled:false,intervalMinutes:10,parseLimit:3}),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[results,setResults]=useState(null),[q,setQ]=useState(''),[status,setStatus]=useState('all'),[missing,setMissing]=useState(null);
  const load=async(silent=false)=>{try{const r=await api.admin('/openlist');setInfo(r.data);const c=r.data?.config||{};setF(x=>({...x,url:c.url||x.url,publicPathPrefix:c.publicPathPrefix||'/d/a/app/',apiBasePath:c.apiBasePath||'/',enabled:c.enabled!==false,token:''}));setSchedule(r.data?.scheduler?{enabled:!!r.data.scheduler.enabled,intervalMinutes:Number(r.data.scheduler.intervalMinutes||10),parseLimit:Number(r.data.scheduler.parseLimit||3)}:{enabled:false,intervalMinutes:10,parseLimit:3})}catch(e){if(!silent)setNote(e.message)}};
  const loadResults=async(page=1,nextQ=q,nextStatus=status)=>{try{const r=await api.admin(`/openlist/results?page=${page}&pageSize=50&status=${encodeURIComponent(nextStatus)}&q=${encodeURIComponent(nextQ||'')}`);setResults({items:r.data||[],meta:r.meta||{}})}catch(e){setNote(e.message)}};
  useEffect(()=>{load();loadResults(1,'','all')},[]);
  const taskState=info?.task?.state||'idle',running=['queued','running'].includes(taskState);
  useEffect(()=>{if(!running)return;const id=setInterval(()=>load(true),2000);return()=>clearInterval(id)},[running]);
  useEffect(()=>{if(['success','failed'].includes(taskState))loadResults(1,q,status)},[taskState]);
  const save=async()=>{setBusy(true);setNote('');try{const body={url:f.url,publicPathPrefix:f.publicPathPrefix,apiBasePath:f.apiBasePath,enabled:!!f.enabled};if(f.token.trim())body.token=f.token.trim();await api.admin('/openlist',{method:'PUT',body:JSON.stringify(body)});setNote('OpenList 配置已保存');await load()}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const saveSchedule=async()=>{setBusy(true);setNote('');try{await api.admin('/openlist/schedule',{method:'PUT',body:JSON.stringify({enabled:!!schedule.enabled,intervalMinutes:Number(schedule.intervalMinutes),parseLimit:Number(schedule.parseLimit)})});setNote('定时解析设置已保存');await load()}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const test=async()=>{setBusy(true);setNote('正在测试 OpenList…');try{const r=await api.admin('/openlist/test',{method:'POST',body:'{}'});setNote(`连接正常 · 目录条目 ${Number(r.data.total||0).toLocaleString()} · ${r.data.provider||'unknown'}`)}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const sync=async(parseLimit,forceListRefresh=false)=>{if(parseLimit>0&&!confirm(`后台最多解析 ${parseLimit} 个新增/变化 IPA，继续？`))return;try{await api.admin('/openlist/sync',{method:'POST',body:JSON.stringify({parseLimit,forceListRefresh})});setNote(parseLimit?'解析任务已启动':'MD5 扫描任务已启动');await load(true)}catch(e){setNote(e.message)}};
  const loadMissing=async()=>{try{const r=await api.admin('/openlist/missing?page=1&pageSize=100');setMissing(r)}catch(e){setNote(e.message)}};
  const c=info?.cache||{},task=info?.task||{},p=task.progress||{},rm=results?.meta||{},counts=rm.counts||{};
  return <div className="admin-panel"><h2>OpenList IPA 元数据</h2><p>负责发现 IPA、MD5 对比和 Range 解析。解析后的数据库写回由“数据同步”单独控制。</p>{note&&<div className="toast">{note}</div>}<div className="form-grid"><Input l="OpenList URL" k="url" f={f} s={setF}/><Input l={info?.config?.tokenConfigured?'Token（留空不修改）':'只读 Token'} k="token" f={f} s={setF} type="password"/><Input l="公开下载路径前缀" k="publicPathPrefix" f={f} s={setF}/><Input l="API Base Path" k="apiBasePath" f={f} s={setF}/><label>启用<input type="checkbox" checked={!!f.enabled} onChange={e=>setF({...f,enabled:e.target.checked})}/></label></div><div className="actions"><button className="primary" disabled={busy} onClick={save}>保存配置</button><button disabled={busy||!info?.config?.tokenConfigured} onClick={test}>测试连接</button><button disabled={running||!info?.config?.tokenConfigured} onClick={()=>sync(0,true)}>后台扫描 MD5</button><button disabled={running||!info?.config?.tokenConfigured} onClick={()=>sync(5,false)}>后台解析 5 个</button></div>
  <div className="admin-panel"><h3>定时解析</h3><div className="form-grid"><label>启用定时<input type="checkbox" checked={!!schedule.enabled} onChange={e=>setSchedule({...schedule,enabled:e.target.checked})}/></label><label>每 X 分钟<input type="number" min="5" max="1440" value={schedule.intervalMinutes} onChange={e=>setSchedule({...schedule,intervalMinutes:e.target.value})}/></label><label>每次解析 X 个<input type="number" min="1" max="20" value={schedule.parseLimit} onChange={e=>setSchedule({...schedule,parseLimit:e.target.value})}/></label></div><div className="actions"><button className="primary" disabled={busy} onClick={saveSchedule}>保存定时设置</button></div></div>
  <div className="stat-grid"><Card t="缓存文件" v={c.files}/><Card t="已解析" v={c.parsed}/><Card t="待解析" v={c.pending}/><Card t="解析失败" v={c.failed}/></div>
  {taskState!=='idle'&&<div className="admin-panel"><h3>后台任务实时进度</h3><div className="row"><b>{taskState} · {task.stage||'—'}</b><span>{task.message||'—'}</span></div><div className="row"><b>数据库匹配</b><span>引用 {p.databaseRefs||0} · 唯一 IPA {p.uniqueFiles||0} · 缺失 {p.missingFiles||0}</span></div><div className="row"><b>IPA 解析</b><span>{p.parseDone||0}/{p.parseTarget||0} · 成功 {p.parsedSuccess||0} · 失败 {p.parsedFailed||0}</span></div></div>}
  <div className="admin-panel"><h3>解析结果库</h3><div className="inline-form"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索 App / Bundle ID / 版本 / IPA"/><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">全部</option><option value="parsed">已解析</option><option value="pending">待解析</option><option value="failed">解析失败</option><option value="mismatch">版本/大小异常</option></select><button onClick={()=>loadResults(1,q,status)}>搜索</button><button onClick={loadMissing}>缺失条目</button></div><div className="row"><b>结果统计</b><span>全部 {counts.all||0} · 已解析 {counts.parsed||0} · 待解析 {counts.pending||0} · 失败 {counts.failed||0} · 异常 {counts.mismatch||0}</span></div><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">App</th><th align="left">源 / IPA 版本</th><th align="left">IPA 信息</th><th align="left">状态</th></tr></thead><tbody>{results?.items?.map(x=><tr key={x.appKey} style={{borderTop:'1px solid #e5e7eb'}}><td style={{padding:8}}><b>{x.appName||x.packageName||x.fileName}</b><br/><small>{x.sourceName} · ID {x.legacyId}</small></td><td style={{padding:8}}>{x.sourceVersion||'—'} → {x.packageVersion||'—'} {x.packageBuild?`(${x.packageBuild})`:''}</td><td style={{padding:8,wordBreak:'break-all'}}>{x.bundleId||'—'}<br/>iOS {x.minimumIos||'—'} · {fmtBytes(x.size)}</td><td style={{padding:8}}>{x.parseStatus==='parsed'?'已解析':x.parseStatus==='failed'?'失败':'待解析'}{x.mismatch?' · 需核对':''}</td></tr>)}</tbody></table></div>{results?.meta&&<div className="actions"><button disabled={Number(rm.page||1)<=1} onClick={()=>loadResults(Number(rm.page||1)-1,q,status)}>上一页</button><span>第 {rm.page||1} 页 · {rm.total||0} 条</span><button disabled={Number(rm.page||1)*Number(rm.pageSize||50)>=Number(rm.total||0)} onClick={()=>loadResults(Number(rm.page||1)+1,q,status)}>下一页</button></div>}</div>
  {missing&&<div className="admin-panel"><h3>缺失 IPA 对应数据库条目</h3>{missing.data?.map(x=><div className="row" key={x.appKey}><b>{x.sourceName} · ID {x.legacyId} · {x.name}</b><span>{x.version||'—'} · {x.apiPath}</span></div>)}</div>}
  </div>
}

export function PasswordManager(){
  const[f,setF]=useState({currentPassword:'',newPassword:'',confirmPassword:''}),[m,setM]=useState('');
  const submit=async()=>{setM('');if(f.newPassword!==f.confirmPassword)return setM('两次输入的新密码不一致');try{await api.admin('/account/password',{method:'POST',body:JSON.stringify(f)});alert('密码修改成功，请重新登录');window.location.assign('/login')}catch(e){setM(e.message)}};
  return <div className="admin-panel"><h2>修改管理员密码</h2><p>修改成功后当前登录会话立即失效。</p>{m&&<div className="toast">{m}</div>}<div className="form-grid"><Input l="当前密码" k="currentPassword" f={f} s={setF} type="password"/><Input l="新密码（至少 10 位）" k="newPassword" f={f} s={setF} type="password"/><Input l="确认新密码" k="confirmPassword" f={f} s={setF} type="password"/></div><div className="actions"><button className="primary" onClick={submit}>修改密码</button></div></div>
}

export function SystemUpdate(){
  const[info,setInfo]=useState(null),[channel,setChannel]=useState('preview'),[loading,setLoading]=useState(true),[error,setError]=useState('');
  const load=async(silent=false)=>{if(!silent)setLoading(true);try{const r=await api.admin('/system/update');setInfo(r.data);setChannel(c=>r.data?.channels?.[c]?c:(r.data?.defaultChannel||'preview'));setError('')}catch(e){if(!silent)setError(e.message)}finally{if(!silent)setLoading(false)}};
  useEffect(()=>{load()},[]);
  useEffect(()=>{if(!['queued','running'].includes(info?.status?.state))return;const id=setInterval(()=>load(true),2500);return()=>clearInterval(id)},[info?.status?.state]);
  const selected=info?.channels?.[channel]||null,state=info?.status?.state||'idle',running=['queued','running'].includes(state);
  const start=async()=>{if(!selected?.hasUpdate)return;if(!confirm(`确定从${selected.label}一键更新到 ${selected.latestVersion}？更新前会自动备份，失败会自动回滚。`))return;setError('');try{const r=await api.admin('/system/update',{method:'POST',body:JSON.stringify({channel})});setInfo(x=>({...x,status:r.data}));setTimeout(()=>load(true),1000)}catch(e){setError(e.message)}};
  return <div className="admin-panel"><h2>GitHub 在线更新</h2><p>Preview 跟随当前开发分支最近一次通过 CI 的构建；禁止降级。</p>{loading&&<p>正在检查…</p>}{error&&<div className="toast">{error}</div>}{info&&<><div className="row"><b>当前版本</b><span>{info.currentVersion}</span></div><div className="row"><b>更新通道</b><select value={channel} disabled={running} onChange={e=>setChannel(e.target.value)}><option value="preview">预览版 Preview</option><option value="stable">稳定版 Stable</option></select></div><div className="row"><b>目标版本</b><span>{selected?.latestVersion||'暂未获取'}</span></div><div className="row"><b>任务状态</b><span>{state} · {info.status?.message||'—'}</span></div><div className="actions"><button onClick={()=>load()} disabled={running}>检查更新</button><button className="primary" onClick={start} disabled={running||!selected?.hasUpdate}>{running?'正在更新…':selected?.hasUpdate?`一键更新到 ${selected.latestVersion}`:'已是最新'}</button></div></>}</div>
}
