import {useEffect,useMemo,useState} from 'react';
import {api} from '../lib/api';
import {Card} from './AdminCorePanels';

const emptyCfg={enabled:false,allowCopy:false,allowRename:false,allowQuarantine:false,quarantineFolder:'.zonoe-quarantine',aliasMountPath:'',mounts:[]};

export default function AdminReplicaPanel(){
  const[state,setState]=useState(null),[cfg,setCfg]=useState(emptyCfg),[preview,setPreview]=useState(null),[note,setNote]=useState(''),[busy,setBusy]=useState(false);
  const load=async()=>{try{const r=await api.admin('/openlist/replicas');setState(r.data);setCfg({...emptyCfg,...(r.data?.config||{}),mounts:r.data?.config?.mounts||[]})}catch(e){setNote(e.message)}};
  useEffect(()=>{load()},[]);
  const mounts=useMemo(()=>new Map((cfg.mounts||[]).map(x=>[Number(x.storageId),x])),[cfg.mounts]);
  const storageRows=(state?.storages||[]).map(s=>({s,m:mounts.get(Number(s.id))}));
  const updateMount=(s,patch)=>{const current=mounts.get(Number(s.id))||{storageId:s.id,mountPath:s.mountPath,rootPath:s.mountPath,label:s.remark||s.mountPath,enabled:true,writable:false};const next={...current,...patch,storageId:s.id,mountPath:s.mountPath};setCfg(x=>({...x,mounts:[...(x.mounts||[]).filter(m=>Number(m.storageId)!==Number(s.id)),next]}))};
  const toggleStorage=(s,on)=>{if(on)updateMount(s,{enabled:true});else setCfg(x=>({...x,mounts:(x.mounts||[]).filter(m=>Number(m.storageId)!==Number(s.id))}))};
  const save=async()=>{setBusy(true);setNote('');try{await api.admin('/openlist/replicas',{method:'PUT',body:JSON.stringify(cfg)});setNote('云盘副本配置已保存');await load()}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const runPreview=async()=>{setBusy(true);setNote('正在读取数据库和多个网盘目录…');try{const r=await api.admin('/openlist/replicas/preview',{method:'POST',body:'{}'});setPreview(r.data);setNote('对账完成')}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const sync=async()=>{if(!confirm('把当前缺失副本通过 OpenList 跨存储复制补齐？本次最多提交 20 个复制任务。'))return;setBusy(true);try{const r=await api.admin('/openlist/replicas/sync',{method:'POST',body:JSON.stringify({limit:20})});setNote(`已提交 ${r.data.queued?.length||0} 个复制任务，失败 ${r.data.failed?.length||0} 个。OpenList 可能在后台继续复制，稍后重新对账确认。`)}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const rename=async(storageId,x)=>{if(!confirm(`确认把 ${x.fromRelative} 改名为 ${x.toRelative}？此建议来自相同 MD5。`))return;setBusy(true);try{await api.admin('/openlist/replicas/rename',{method:'POST',body:JSON.stringify({storageId,fromRelative:x.fromRelative,toRelative:x.toRelative})});setNote('名称修复完成，请重新对账');await runPreview()}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const quarantine=async(storageId,relativePath)=>{if(!confirm(`把多余 IPA 移到隔离区？\n${relativePath}\n\n不会永久删除。`))return;setBusy(true);try{await api.admin('/openlist/replicas/quarantine',{method:'POST',body:JSON.stringify({items:[{storageId,relativePath}]})});setNote('已移动到隔离区，请重新对账');await runPreview()}catch(e){setNote(e.message)}finally{setBusy(false)}};
  const aliases=state?.alias?.candidates||[],pAlias=preview?.alias?.preferred||state?.alias?.preferred;
  return <div className="admin-panel"><h2>云盘副本管理</h2><p>数据库下载地址是期望清单；实体网盘保存副本；OpenList Alias 负责最终分流。ZONOE 只调用 OpenList 文件操作 API，不中转 IPA 数据。</p>{note&&<div className="toast">{note}</div>}
    {state?.storageError&&<div className="toast">无法读取 OpenList 挂载列表：{state.storageError}。此功能需要 Token 具备读取存储列表的权限。</div>}
    <div className="form-grid"><label>启用副本管理<input type="checkbox" checked={!!cfg.enabled} onChange={e=>setCfg({...cfg,enabled:e.target.checked})}/></label><label>允许副本复制<input type="checkbox" checked={!!cfg.allowCopy} onChange={e=>setCfg({...cfg,allowCopy:e.target.checked})}/></label><label>允许名称修复<input type="checkbox" checked={!!cfg.allowRename} onChange={e=>setCfg({...cfg,allowRename:e.target.checked})}/></label><label>允许移动到隔离区<input type="checkbox" checked={!!cfg.allowQuarantine} onChange={e=>setCfg({...cfg,allowQuarantine:e.target.checked})}/></label><label>隔离目录名<input value={cfg.quarantineFolder||''} onChange={e=>setCfg({...cfg,quarantineFolder:e.target.value})}/></label><label>Alias 分流挂载路径<input placeholder="例如 /app-download" value={cfg.aliasMountPath||''} onChange={e=>setCfg({...cfg,aliasMountPath:e.target.value})}/></label></div>
    <div className="admin-panel"><h3>OpenList 挂载网盘</h3><p>勾选真正保存 IPA 的实体存储。副本目录可以是挂载根目录下的子目录，例如 <code>/天翼01/app</code>。只有标记“可写”的盘才会接收复制、改名或隔离操作。</p><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse'}}><thead><tr><th align="left">管理</th><th align="left">挂载/驱动</th><th align="left">副本目录</th><th align="left">可写</th><th align="left">状态</th></tr></thead><tbody>{storageRows.map(({s,m})=>{const alias=String(s.driver).toLowerCase()==='alias';return <tr key={s.id} style={{borderTop:'1px solid #e5e7eb'}}><td style={{padding:8}}><input type="checkbox" disabled={alias} checked={!!m} onChange={e=>toggleStorage(s,e.target.checked)}/>{alias&&<small> 分流盘</small>}</td><td style={{padding:8}}><b>{s.mountPath}</b><br/><small>{s.driver}{s.remark?` · ${s.remark}`:''}</small></td><td style={{padding:8}}>{m?<input style={{minWidth:260}} value={m.rootPath||s.mountPath} onChange={e=>updateMount(s,{rootPath:e.target.value})}/>:<span>—</span>}</td><td style={{padding:8}}>{m?<input type="checkbox" checked={!!m.writable} onChange={e=>updateMount(s,{writable:e.target.checked})}/>:<span>—</span>}</td><td style={{padding:8}}>{s.disabled?'已禁用':s.status||'unknown'}</td></tr>})}</tbody></table></div><div className="actions"><button className="primary" disabled={busy} onClick={save}>保存副本配置</button><button disabled={busy||!cfg.enabled} onClick={runPreview}>开始多网盘对账</button><button disabled={busy||!preview||!cfg.allowCopy} onClick={sync}>补齐缺失副本（20 个）</button></div></div>
    <div className="admin-panel"><h3>OpenList Alias 分流检查</h3>{pAlias?<><div className="row"><b>{pAlias.mountPath}</b><span>覆盖 {pAlias.matchedCount}/{pAlias.requiredCount} 个已选副本目录 · {pAlias.status||'unknown'}</span></div><p>{pAlias.matchedCount===pAlias.requiredCount&&pAlias.requiredCount>0?'Alias 已覆盖所有已选网盘目录。请在 OpenList 中把读取冲突策略设为“按文件负载均衡”。':'Alias 尚未覆盖全部已选网盘目录，暂时不能认为分流配置完整。'}</p>{Object.keys(pAlias.policyHints||{}).length>0&&<small>OpenList 返回的策略线索：{JSON.stringify(pAlias.policyHints)}</small>}</>:<p>{aliases.length?'已发现 Alias，但当前没有匹配到你配置的分流挂载路径。':'未发现 Alias 存储。请先在 OpenList 创建 Alias，把各实体网盘的副本目录合并。'}</p>}</div>
    {preview&&<><div className="stat-grid"><Card t="数据库期望 IPA" v={preview.expectedCount}/><Card t="管理网盘" v={preview.mounts?.length}/><Card t="忽略数据库地址" v={preview.ignoredDatabaseRefs}/><Card t="软件源读取错误" v={preview.sourceErrors?.length}/></div>{preview.mounts?.map(m=><div className="admin-panel" key={m.storageId}><h3>{m.label||m.mountPath}</h3>{m.error?<div className="toast">扫描失败：{m.error}</div>:<><div className="row"><b>{m.rootPath}</b><span>现有 {m.total} · 正常 {m.present} · 缺失 {m.missing?.length||0} · 多余 {m.extra?.length||0}</span></div>{m.renameSuggestions?.length>0&&<><h4>可按 MD5 修复名称</h4>{m.renameSuggestions.slice(0,30).map(x=><div className="row" key={`${x.fromRelative}->${x.toRelative}`}><span style={{wordBreak:'break-all'}}>{x.fromRelative} → <b>{x.toRelative}</b></span><button disabled={busy||!cfg.allowRename||!m.writable} onClick={()=>rename(m.storageId,x)}>按建议改名</button></div>)}</>}{m.extra?.length>0&&<><h4>数据库不存在的多余 IPA</h4>{m.extra.slice(0,50).map(x=><div className="row" key={x.relativePath}><span style={{wordBreak:'break-all'}}>{x.relativePath}</span><button disabled={busy||!cfg.allowQuarantine||!m.writable} onClick={()=>quarantine(m.storageId,x.relativePath)}>移到隔离区</button></div>)}</>}{m.missing?.length>0&&<details><summary>查看缺失 {m.missing.length} 个</summary>{m.missing.slice(0,100).map(x=><div className="row" key={x.relativePath}><span style={{wordBreak:'break-all'}}>{x.relativePath}</span><small>{x.apps?.map(a=>a.name).filter(Boolean).join(' / ')||'—'}</small></div>)}</details>}</>}</div>)}</>}
  </div>
}
